# exclude django-generated files
extend-exclude = [
  "manage.py",
  "*/migrations/*.py",
  "/usr/*",
  "mysite/*",
  "*/__init__.py",
  "*/admin.py",
  "*/urls.py",
  "*/apps.py",
]

target-version = "py311"

[lint]
# Add checking for docstrings, naming convention and line too long, in addition
# to Ruff's default linting rules
# By default, the maximum line length is 88 characters, which is the same as
# Black's coding style
extend-select = ["D", "N", "E501"]

[lint.pydocstyle]
# Set docstrings convention to PEP257
convention = "pep257"
